"ignore"; from frames import *

# Here we define all the player's moves.

playerUpB = FrameSequence(16)

playerUpB.setall("attack", 10.0)
playerUpB.setall("vel_self", Vec2(0, -20))
playerUpB.setall("vel_other", Vec2(0, -9))
playerUpB.setall("gravity", 0.0)
playerUpB.setall("armor", 0.0)
playerUpB.setall("stun_self", True)
playerUpB.setall("stun_other", 40)
playerUpB.frames[15].vel_self = Vec2(0, -10)

playerSideB = FrameSequence(200)
_startlag = range(0, 40)
_active = range(40, 140)
_endlag = range(140, 200)

playerSideB.setrange(_startlag, "attack", 0.0)
playerSideB.setrange(_startlag, "vel_self", Vec2(0, 0))
playerSideB.setrange(_startlag, "vel_other", Vec2(0, 0))
playerSideB.setrange(_startlag, "gravity", 0.0)
playerSideB.setrange(_startlag, "armor", 0.0)
playerSideB.setrange(_startlag, "stun_self", True)
playerSideB.setrange(_startlag, "stun_other", 0)

playerSideB.setrange(_active, "attack", 25.0)
playerSideB.setrange(_active, "vel_self", Vec2(-8, 0))
playerSideB.setrange(_active, "vel_other", Vec2(-25, 0))
playerSideB.setrange(_active, "gravity", 0.5)
playerSideB.setrange(_active, "armor", 0.8)
playerSideB.setrange(_active, "stun_self", True)
playerSideB.setrange(_active, "stun_other", 125)

playerSideB.setrange(_endlag, "attack", 0.0)
playerSideB.setrange(_endlag, "vel_self", Vec2(-2, 0))
playerSideB.setrange(_endlag, "vel_other", Vec2(0, 0))
playerSideB.setrange(_endlag, "gravity", 1.0)
playerSideB.setrange(_endlag, "armor", 0.0)
playerSideB.setrange(_endlag, "stun_self", True)
playerSideB.setrange(_endlag, "stun_other", 0)

playerDownB = FrameSequence(25)
_startlag = range(0, 3)
_active = range(3, 20)
_endlag = range(20, 25)

playerDownB.setrange(_startlag, "attack", 0.0)
playerDownB.setrange(_startlag, "vel_self", Vec2(0, 0))
playerDownB.setrange(_startlag, "vel_other", Vec2(0, 0))
playerDownB.setrange(_startlag, "gravity", 1.0)
playerDownB.setrange(_startlag, "armor", 0.0)
playerDownB.setrange(_startlag, "stun_self", True)
playerDownB.setrange(_startlag, "stun_other", 0)

playerDownB.setrange(_active, "attack", 0.0)
playerDownB.setrange(_active, "vel_self", Vec2(0, 0))
playerDownB.setrange(_active, "vel_other", Vec2(0, 0))
playerDownB.setrange(_active, "gravity", 0.0)
playerDownB.setrange(_active, "armor", 1.0)
playerDownB.setrange(_active, "stun_self", False)
playerDownB.setrange(_active, "stun_other", 0)

playerDownB.setrange(_endlag, "attack", 0.0)
playerDownB.setrange(_endlag, "vel_self", Vec2(0, 0))
playerDownB.setrange(_endlag, "vel_other", Vec2(0, 0))
playerDownB.setrange(_endlag, "gravity", 1.0)
playerDownB.setrange(_endlag, "armor", 0.0)
playerDownB.setrange(_endlag, "stun_self", False)
playerDownB.setrange(_endlag, "stun_other", 0)